name: Deploy to Azure Function App

on:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Deploy Azure Functions'
      uses: Azure/functions-action@v1
      id: deploy-to-function
      with:
        app-name: 'cippv4yw3'
        slot-name: 'Production'
        package: '.'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B33FBC274CAF482A90383F8C32B226DC }}
