name: Deploy to cipppwrro Function App

on:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Deploy Azure Functions'
      uses: Azure/functions-action@v1
      id: deploy-to-function
      with:
        app-name: 'cipppwrro'
        package: '.'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4647AAE2F2FE4C5E95AFEB2697008DBF }}
