name: Deploy Function App

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: 'cippv4yw3'
          package: '.'
          publish-profile: ${{ secrets.CIPPV4YW3_PUBLISH_PROFILE }}
